### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by GeekNOmore** [TheSlientnight/douyu_helper#15]
`2022-07-02 02:08:12 - 【INFO】: ------登录检查开始------
[12](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:13)
2022-07-02 02:08:13 - 【INFO】: Cookie有效,登陆成功
[13](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:14)
2022-07-02 02:08:13 - 【INFO】: ------登录检查结束------
[14](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:15)
2022-07-02 02:08:13 - 【INFO】: ------正在获取荧光棒------
[15](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:16)
2022-07-02 02:08:14 - 【INFO】: 打开直播间
[16](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:17)
2022-07-02 02:08:15 - 【INFO】: 刷新页面以完成登录
[17](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:18)
Traceback (most recent call last):
[18](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:19)
  File "main.py", line 60, in <module>
[19](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:20)
    run()
[20](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:21)
  File "main.py", line 18, in run
[21](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:22)
    get_glow()
[22](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:23)
  File "/home/runner/work/douyu_helper/douyu_helper/common/dy_glows.py", line 29, in get_glow
[23](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:24)
    go_room()
[24](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:25)
  File "/home/runner/work/douyu_helper/douyu_helper/common/dy_glows.py", line 124, in go_room
[25](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:26)
    WebDriverWait(driver, 30, 0.5).until(lambda drivers: drivers.find_element_by_xpath("/html/body/section/header/div"
[26](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:27)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 81, in until
[27](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:28)
    value = method(self._driver)
[28](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:29)
  File "/home/runner/work/douyu_helper/douyu_helper/common/dy_glows.py", line 124, in <lambda>
[29](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:30)
    WebDriverWait(driver, 30, 0.5).until(lambda drivers: drivers.find_element_by_xpath("/html/body/section/header/div"
[30](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:31)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'
[31](https://github.com/GeekNOmore/douyu_helper/runs/7159000335?check_suite_focus=true#step:6:32)
Error: Process completed with exit code 1.`

**Comment by BigFaceCat5233** [comment]
WebDriver版本和chrome版本对不上 fork我的仓库 我刚改好不用手动下载最新的WebDriver 或者你手动下载到chrome文件夹也行 有两个文件 没有后缀的那个是linux版本 还有一个是win版本的 如果跑actions应该不用下win版本的也行

**Comment by BigFaceCat5233** [comment]
我不会写python不知道对没对 所以就不合并到这个仓库了

**Comment by TheSlientnight** [comment]
稍后修改

**Comment by BigFaceCat5233** [comment]
提交了修改 作者大大看看对不对

**Comment by GeekNOmore** [comment]
> WebDriver版本和chrome版本对不上 fork我的仓库 我刚改好不用手动下载最新的WebDriver 或者你手动下载到chrome文件夹也行 有两个文件 没有后缀的那个是linux版本 还有一个是win版本的 如果跑actions应该不用下win版本的也行

应该不是版本的问题. GitHub 用的 chrome 版本很迷. 我这边换你的 chromedrive 提示
`selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
[41](https://github.com/GeekNOmore/douyu_helper/runs/7188927707?check_suite_focus=true#step:6:42)
Current browser version is 103.0.5060.53 with binary path /usr/bin/google-chrome`

**Comment by BigFaceCat5233** [comment]
> 稍后修改

提交了修改 作者大大看看对不对

**Comment by TheSlientnight** [comment]
问题已经修复，请重新拉取

**Comment by TheSlientnight** [comment]
> > 稍后修改
> 
> 提交了修改 作者大大看看对不对

没什么问题，selenium官方在新的版本中删除了我之前使用的方法，因此需要修改
