### ISSUE TITLE
执行Actions时报错,尝试过重新Fork并更换cookie,仍然报错

### ISSUE THREAD

**Issue by lenewing3** [TheSlientnight/douyu_helper#7]
`Run sudo cp -p ./chrome/chromedriver /usr/bin/
2021-09-29 02:05:35 - 【INFO】: ------登录检查开始------
2021-09-29 02:05:38 - 【INFO】: Cookie有效,登陆成功
2021-09-29 02:05:38 - 【INFO】: ------登录检查结束------
2021-09-29 02:05:38 - 【INFO】: ------正在获取荧光棒------
2021-09-29 02:05:39 - 【INFO】: 打开直播间
2021-09-29 02:05:41 - 【INFO】: 刷新页面以完成登录
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    run()
  File "main.py", line 18, in run
    get_glow()
  File "/home/runner/work/douyu_helper/douyu_helper/common/dy_glows.py", line 25, in get_glow
    go_room()
  File "/home/runner/work/douyu_helper/douyu_helper/common/dy_glows.py", line 117, in go_room
    WebDriverWait(driver, 30, 0.5).until(lambda drivers: drivers.find_element_by_xpath("/html/body/section/header/div"
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Error: Process completed with exit code 1.`  

以上是working的输出,请问这是哪里出问题了呢??

**Comment by TheSlientnight** [comment]
selenium webdriver版本的问题，这个脚本需要定期更新这个webdriver的版本，所以需要辛苦定期pull request
斗鱼无法通过接口直接获得到荧光棒，需要打开页面浏览一下才可以，因此这里用到了selenium，晚点更新后告知到你

**Comment by TheSlientnight** [comment]
服务器网络存在一定的问题，因为是github自己的服务器向斗鱼进行请求，所以有可能遇到波动导致无法正常请求到斗鱼的服务器
出现此类问题一般是服务器区域出现了问题，如果需要追求稳定请在自己的服务器内搭建代码，但是如果使用github的定时任务则可能会出现这类问题，目前我这里也无法完美解决

**Comment by lenewing3** [comment]
万分感谢作者的回答,工具很好用,谢谢了,感恩!!
