### ISSUE TITLE
正常复制的cookie报 UnicodeEncodeError 

### ISSUE THREAD

**Issue by LunaticTian** [TheSlientnight/douyu_helper#9]
cookie 是按说明正常复制的，但是依旧报错。
> 2021-10-10 16:27:33 - 【INFO】: ------登录检查开始------
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    run()
  File "main.py", line 14, in run
    login_res = is_login()
  File "/home/runner/work/douyu_helper/douyu_helper/common/login_check.py", line 14, in is_login
    login = dyreq.request("get", login_url).json()
  File "/home/runner/work/douyu_helper/douyu_helper/common/douyu_request.py", line 23, in request
    return self.session.request(method, url=url, headers=self.header, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1322, in _send_request
    self.putheader(hdr, value)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1254, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 675-678: ordinal not in range(256)
Error: Process completed with exit code 1.

**Comment by LunaticTian** [comment]
> @LunaticTian我遇到了这个问题，是发现中包含中文字符导致cookie的名字，如果你的斗鱼也修改了昵称是中文，那么就会出现这个问题，可以手动cookie中的改成英文的，不影响解析cookie，亲测原来。

acf_nickname中应用名可能为中文，更改为英文成功！ 感谢！
